#!/bin/sh
# Generates .env with secure random keys if it doesn't already exist.
set -e

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
  exit 0
fi

ENCRYPTION_KEY=$(openssl rand -hex 32)
MCP_TOKEN=$(openssl rand -base64 24 | tr '+/' '-_' | tr -d '=')

mkdir -p ./data

cat > "$ENV_FILE" <<EOF
# Generated by db-mcp setup — do not commit this file
DATABASE_PATH=./data/db-mcp.sqlite
ENCRYPTION_KEY=$ENCRYPTION_KEY
MCP_TOKEN=$MCP_TOKEN
PORT=4080
EOF

echo "✓ Generated .env with secure random keys"
echo ""
echo "  MCP_TOKEN: $MCP_TOKEN"
echo ""
echo "  Copy this token — you'll need it to connect your AI tool."
